/*jshint esversion: 6 */
const { Schema, model } = require('mongoose');

const vueloSchema = new Schema({
    Year: { type: Number },
    Month: { type: Number },
    DayofMonth: { type: Number },
    DayOfWeek: { type: Number },
    DepTime: { type: Number },
    CRSDepTime: { type: Number },
    ArrTime: { type: Number },
    CRSArrTime: { type: Number },
    UniqueCarrier: { type: String },
    FlightNum: { type: Number },
    TailNum: { type: String },
    ActualElapsedTime: { type: Number },
    CRSElapsedTime: { type: Number },
    AirTime: { type: Number },
    ArrDelay: { type: Number },
    DepDelay: { type: Number },
    Origin: { type: String },
    Dest: { type: String },
    Distance: { type: Number },
    TaxiIn: { type: Number },
    TaxiOut: { type: Number },
    Cancelled: { type: Number },
    CancellationCode: { type: String },
    Diverted: { type: Number },
    CarrierDelay: { type: Number },
    WeatherDelay: { type: Number },
    NASDelay: { type: Number },
    SecurityDelay: { type: Number },
    LateAircraftDelay: { type: Number }
});

module.exports = {
    'c88': model('c88', vueloSchema),
    'c87': model('c87', vueloSchema),
    'c89': model('c89', vueloSchema),
    'c90': model('c90', vueloSchema),
    'c91': model('c91', vueloSchema),
    'c92': model('c92', vueloSchema),
    'c93': model('c93', vueloSchema),
    'c94': model('c94', vueloSchema),
    'c95': model('c95', vueloSchema),
    'c96': model('c96', vueloSchema),
    'c97': model('c97', vueloSchema),
    'c98': model('c98', vueloSchema),
    'c99': model('c99', vueloSchema),
    'c00': model('c00', vueloSchema),
    'c01': model('c01', vueloSchema),
    'c02': model('c02', vueloSchema),
    'c03': model('c03', vueloSchema),
    'c04': model('c04', vueloSchema),
    'c05': model('c05', vueloSchema),
    'c06': model('c06', vueloSchema),
    'c07': model('c07', vueloSchema),
    'c08': model('c08', vueloSchema),
};